/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef PHP_LMDB_H
#define PHP_LMDB_H

extern zend_module_entry lmdb_module_entry;
#define phpext_lmdb_ptr &lmdb_module_entry

#ifdef PHP_WIN32
# define PHP_LMDB_API __declspec(dllexport)
#else
# define PHP_LMDB_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(lmdb);
PHP_MSHUTDOWN_FUNCTION(lmdb);
PHP_RINIT_FUNCTION(lmdb);
PHP_RSHUTDOWN_FUNCTION(lmdb);
PHP_MINFO_FUNCTION(lmdb);

ZEND_NAMED_FUNCTION(_wrap_MDB_val_mv_size_set);
ZEND_NAMED_FUNCTION(_wrap_MDB_val_mv_size_get);
ZEND_NAMED_FUNCTION(_wrap_MDB_val_mv_data_set);
ZEND_NAMED_FUNCTION(_wrap_MDB_val_mv_data_get);
ZEND_NAMED_FUNCTION(_wrap_new_MDB_val);
ZEND_NAMED_FUNCTION(_wrap_MDB_stat_ms_psize_set);
ZEND_NAMED_FUNCTION(_wrap_MDB_stat_ms_psize_get);
ZEND_NAMED_FUNCTION(_wrap_MDB_stat_ms_depth_set);
ZEND_NAMED_FUNCTION(_wrap_MDB_stat_ms_depth_get);
ZEND_NAMED_FUNCTION(_wrap_MDB_stat_ms_branch_pages_set);
ZEND_NAMED_FUNCTION(_wrap_MDB_stat_ms_branch_pages_get);
ZEND_NAMED_FUNCTION(_wrap_MDB_stat_ms_leaf_pages_set);
ZEND_NAMED_FUNCTION(_wrap_MDB_stat_ms_leaf_pages_get);
ZEND_NAMED_FUNCTION(_wrap_MDB_stat_ms_overflow_pages_set);
ZEND_NAMED_FUNCTION(_wrap_MDB_stat_ms_overflow_pages_get);
ZEND_NAMED_FUNCTION(_wrap_MDB_stat_ms_entries_set);
ZEND_NAMED_FUNCTION(_wrap_MDB_stat_ms_entries_get);
ZEND_NAMED_FUNCTION(_wrap_new_MDB_stat);
ZEND_NAMED_FUNCTION(_wrap_MDB_envinfo_me_mapaddr_set);
ZEND_NAMED_FUNCTION(_wrap_MDB_envinfo_me_mapaddr_get);
ZEND_NAMED_FUNCTION(_wrap_MDB_envinfo_me_mapsize_set);
ZEND_NAMED_FUNCTION(_wrap_MDB_envinfo_me_mapsize_get);
ZEND_NAMED_FUNCTION(_wrap_MDB_envinfo_me_last_pgno_set);
ZEND_NAMED_FUNCTION(_wrap_MDB_envinfo_me_last_pgno_get);
ZEND_NAMED_FUNCTION(_wrap_MDB_envinfo_me_last_txnid_set);
ZEND_NAMED_FUNCTION(_wrap_MDB_envinfo_me_last_txnid_get);
ZEND_NAMED_FUNCTION(_wrap_MDB_envinfo_me_maxreaders_set);
ZEND_NAMED_FUNCTION(_wrap_MDB_envinfo_me_maxreaders_get);
ZEND_NAMED_FUNCTION(_wrap_MDB_envinfo_me_numreaders_set);
ZEND_NAMED_FUNCTION(_wrap_MDB_envinfo_me_numreaders_get);
ZEND_NAMED_FUNCTION(_wrap_new_MDB_envinfo);
ZEND_NAMED_FUNCTION(_wrap_mdb_version);
ZEND_NAMED_FUNCTION(_wrap_mdb_strerror);
ZEND_NAMED_FUNCTION(_wrap_mdb_env_copy);
ZEND_NAMED_FUNCTION(_wrap_mdb_env_copyfd);
ZEND_NAMED_FUNCTION(_wrap_mdb_env_copy2);
ZEND_NAMED_FUNCTION(_wrap_mdb_env_copyfd2);
ZEND_NAMED_FUNCTION(_wrap_mdb_env_sync);
ZEND_NAMED_FUNCTION(_wrap_mdb_env_close);
ZEND_NAMED_FUNCTION(_wrap_mdb_env_set_flags);
ZEND_NAMED_FUNCTION(_wrap_mdb_env_set_mapsize);
ZEND_NAMED_FUNCTION(_wrap_mdb_env_set_maxreaders);
ZEND_NAMED_FUNCTION(_wrap_mdb_env_set_maxdbs);
ZEND_NAMED_FUNCTION(_wrap_mdb_env_get_maxkeysize);
ZEND_NAMED_FUNCTION(_wrap_mdb_env_get_userctx);
ZEND_NAMED_FUNCTION(_wrap_mdb_txn_env);
ZEND_NAMED_FUNCTION(_wrap_mdb_txn_commit);
ZEND_NAMED_FUNCTION(_wrap_mdb_txn_abort);
ZEND_NAMED_FUNCTION(_wrap_mdb_txn_reset);
ZEND_NAMED_FUNCTION(_wrap_mdb_txn_renew);
ZEND_NAMED_FUNCTION(_wrap_mdb_dbi_close);
ZEND_NAMED_FUNCTION(_wrap_mdb_drop);
ZEND_NAMED_FUNCTION(_wrap_mdb_get);
ZEND_NAMED_FUNCTION(_wrap_mdb_put);
ZEND_NAMED_FUNCTION(_wrap_mdb_del);
ZEND_NAMED_FUNCTION(_wrap_mdb_cursor_close);
ZEND_NAMED_FUNCTION(_wrap_mdb_cursor_renew);
ZEND_NAMED_FUNCTION(_wrap_mdb_cursor_txn);
ZEND_NAMED_FUNCTION(_wrap_mdb_cursor_dbi);
ZEND_NAMED_FUNCTION(_wrap_mdb_cursor_get);
ZEND_NAMED_FUNCTION(_wrap_mdb_cursor_put);
ZEND_NAMED_FUNCTION(_wrap_mdb_cursor_del);
ZEND_NAMED_FUNCTION(_wrap_mdb_cmp);
ZEND_NAMED_FUNCTION(_wrap_mdb_dcmp);
ZEND_NAMED_FUNCTION(_wrap_mdb_reader_list);
ZEND_NAMED_FUNCTION(_wrap_mdb_env_info);
ZEND_NAMED_FUNCTION(_wrap_mdb_env_stat);
ZEND_NAMED_FUNCTION(_wrap_mdb_set_relctx);
ZEND_NAMED_FUNCTION(_wrap_mdb_stat);
ZEND_NAMED_FUNCTION(_wrap_mdb_reader_check);
ZEND_NAMED_FUNCTION(_wrap_mdb_cursor_count);
ZEND_NAMED_FUNCTION(_wrap_mdb_dbi_flags);
ZEND_NAMED_FUNCTION(_wrap_mdb_env_set_userctx);
ZEND_NAMED_FUNCTION(_wrap_mdb_env_get_userctx_swig);
ZEND_NAMED_FUNCTION(_wrap_mdb_env_get_flags);
ZEND_NAMED_FUNCTION(_wrap_mdb_env_get_path);
ZEND_NAMED_FUNCTION(_wrap_mdb_env_get_fd);
ZEND_NAMED_FUNCTION(_wrap_mdb_env_get_maxreaders);
ZEND_NAMED_FUNCTION(_wrap_mdb_env_create);
ZEND_NAMED_FUNCTION(_wrap_mdb_env_open);
ZEND_NAMED_FUNCTION(_wrap_mdb_txn_begin);
ZEND_NAMED_FUNCTION(_wrap_mdb_dbi_open);
ZEND_NAMED_FUNCTION(_wrap_mdb_cursor_open);
ZEND_NAMED_FUNCTION(_wrap_mdb_val_create);
ZEND_NAMED_FUNCTION(_wrap_mdb_val_size);
ZEND_NAMED_FUNCTION(_wrap_mdb_val_data);
ZEND_NAMED_FUNCTION(_wrap_mdb_stat_psize);
ZEND_NAMED_FUNCTION(_wrap_mdb_stat_depth);
ZEND_NAMED_FUNCTION(_wrap_mdb_stat_branch_pages);
ZEND_NAMED_FUNCTION(_wrap_mdb_stat_leaf_pages);
ZEND_NAMED_FUNCTION(_wrap_mdb_stat_overflow_pages);
ZEND_NAMED_FUNCTION(_wrap_mdb_stat_entries);
ZEND_NAMED_FUNCTION(_wrap_mdb_info_mapaddr);
ZEND_NAMED_FUNCTION(_wrap_mdb_info_mapsize);
ZEND_NAMED_FUNCTION(_wrap_mdb_info_last_pgno);
ZEND_NAMED_FUNCTION(_wrap_mdb_info_last_txnid);
ZEND_NAMED_FUNCTION(_wrap_mdb_info_maxreaders);
ZEND_NAMED_FUNCTION(_wrap_mdb_info_numreaders);
#endif /* PHP_LMDB_H */
